export const INITIAL_ITEMS = [
  'j2zqF9dC/tree.png',
  'bNB1PSzP/elephant.png',
  'YCFLwXnN/queen.png',
  'WzRbSjVQ/zebra.png',
  'j2zqF9dC/tree.png',
  'pXTK3JMk/bison.png',
  '0jtDbbDp/jack.png',
  'Cx4B1Z0d/ten.png',
  'HsV76Wbh/nine.png',
  'qBQ8mZSz/king.png',
  'Kj44pQ3M/rhino.png',
  'j2zqF9dC/tree.png',
  '0Qsp3g9J/ace.png',
  'Kj44pQ3M/rhino.png',
  'pXTK3JMk/bison.png',
  'jdmnmVXd/lion.png',
  'Kj44pQ3M/rhino.png',
  'pXTK3JMk/bison.png',
  'bNB1PSzP/elephant.png',
  'WzRbSjVQ/zebra.png',
  'qBQ8mZSz/king.png',
  'HsV76Wbh/nine.png',
  'Cx4B1Z0d/ten.png',
  'WzRbSjVQ/zebra.png',
  '0jtDbbDp/jack.png',
  'qBQ8mZSz/king.png',
  'jdmnmVXd/lion.png',
  'Cx4B1Z0d/ten.png',
  'YCFLwXnN/queen.png',
  'qBQ8mZSz/king.png',
  'HsV76Wbh/nine.png',
  '0jtDbbDp/jack.png',
  'YCFLwXnN/queen.png',
  'qBQ8mZSz/king.png',
  '0Qsp3g9J/ace.png',
  'Cx4B1Z0d/ten.png',
  '85mhgyCX/flamingo.png',
  'YCFLwXnN/queen.png',
  '0Qsp3g9J/ace.png',
  'pXTK3JMk/bison.png',
  'bNB1PSzP/elephant.png',
  '85mhgyCX/flamingo.png',
  'qBQ8mZSz/king.png',
  '0jtDbbDp/jack.png',
  'bNB1PSzP/elephant.png',
  'Cx4B1Z0d/ten.png',
  'HsV76Wbh/nine.png',
  'YCFLwXnN/queen.png',
  'pXTK3JMk/bison.png',
  'Kj44pQ3M/rhino.png',
  '0jtDbbDp/jack.png',
  'bNB1PSzP/elephant.png',
  'Cx4B1Z0d/ten.png',
  'HsV76Wbh/nine.png',
  '0Qsp3g9J/ace.png',
  'YCFLwXnN/queen.png',
  '0jtDbbDp/jack.png',
  'Cx4B1Z0d/ten.png',
  'pXTK3JMk/bison.png',
  'Kj44pQ3M/rhino.png',
  'jdmnmVXd/lion.png',
  '0Qsp3g9J/ace.png',
  '0jtDbbDp/jack.png',
  'WzRbSjVQ/zebra.png',
  'YCFLwXnN/queen.png',
  'HsV76Wbh/nine.png',
  'HsV76Wbh/nine.png',
  'Cx4B1Z0d/ten.png',
  'Kj44pQ3M/rhino.png',
  'jdmnmVXd/lion.png',
  'Kj44pQ3M/rhino.png',
  '0Qsp3g9J/ace.png',
  'bNB1PSzP/elephant.png',
  '85mhgyCX/flamingo.png',
  '0jtDbbDp/jack.png',
  'WzRbSjVQ/zebra.png',
  'pXTK3JMk/bison.png',
  'HsV76Wbh/nine.png',
  '85mhgyCX/flamingo.png',
  'WzRbSjVQ/zebra.png',
  'pXTK3JMk/bison.png',
  '0Qsp3g9J/ace.png',
  'WzRbSjVQ/zebra.png',
  '85mhgyCX/flamingo.png',
  'bNB1PSzP/elephant.png',
  '0Qsp3g9J/ace.png',
  '85mhgyCX/flamingo.png',
  'qBQ8mZSz/king.png',
  'HsV76Wbh/nine.png',
  'Cx4B1Z0d/ten.png',
  '0jtDbbDp/jack.png',
  'j2zqF9dC/tree.png',
  '85mhgyCX/flamingo.png',
  'jdmnmVXd/lion.png',
  'YCFLwXnN/queen.png',
  'qBQ8mZSz/king.png',
  '0Qsp3g9J/ace.png',
  'j2zqF9dC/tree.png',
  'WzRbSjVQ/zebra.png',
  'Kj44pQ3M/rhino.png',
];

export const INITIAL_ITEMS_GIF: { [key: string]: string } = {
  'bNB1PSzP/elephant.png': 'wBQ79z3X/elephant.gif',
  'YCFLwXnN/queen.png': 'WzTRTRFk/queen.gif',
  'WzRbSjVQ/zebra.png': 'gj00mtTN/zebra.gif',
  'pXTK3JMk/bison.png': 'sDSrScyx/bison.gif',
  '0jtDbbDp/jack.png': 'TwJv5HfX/jack.gif',
  'Cx4B1Z0d/ten.png': 'tCvcmn5P/ten.gif',
  'HsV76Wbh/nine.png': 'g0QRfNZ8/nine.gif',
  'qBQ8mZSz/king.png': 'HkTfytjw/king.gif',
  'Kj44pQ3M/rhino.png': '904jL6S5/rhino.gif',
  '0Qsp3g9J/ace.png': 'rFMyFxG4/ace.gif',
  'jdmnmVXd/lion.png': 'TYmG8XkC/lion.gif',
  '85mhgyCX/flamingo.png': 't4G3grS5/flamingo.gif',
  'j2zqF9dC/tree.png': 'HxXNjTfL/tree.gif',
};
export const SET_RESULT_ITEM: { [key: string]: string } = {
  'bNB1PSzP/elephant.png': 'elephant',
  'YCFLwXnN/queen.png': 'queen',
  'WzRbSjVQ/zebra.png': 'zebra',
  'pXTK3JMk/bison.png': 'bison',
  '0jtDbbDp/jack.png': 'jack',
  'Cx4B1Z0d/ten.png': 'ten',
  'HsV76Wbh/nine.png': 'nine',
  'qBQ8mZSz/king.png': 'king',
  'Kj44pQ3M/rhino.png': 'rhino',
  '0Qsp3g9J/ace.png': 'ace',
  'jdmnmVXd/lion.png': 'lion',
  '85mhgyCX/flamingo.png': 'flamingo',
  'j2zqF9dC/tree.png': 'tree',
};